# (asset, 한국어, 영문/별칭, 근거, 확신)  근거: H=SOURCE.txt 헤더 · F=원본 파일명 · G=glb asset.extras 제목 · T=Sketchfab 제목(SOURCE) · Z=zip 안 파일명 · C=복사(재료와 같은 스킨)
D = []
def a(asset, ko, en, ev, conf='높음'): D.append((asset, ko, en, ev, conf))
# 다른세계
a('다른세계_고죠_사토루','고죠 사토루','Satoru Gojo,Gojo','H 헤더 「Satoru Gojo, 주술회전」')
a('다른세계_김건부','아오키지','쿠잔,Kuzan,Aokiji','H 「쿠잔/아오키지(원피스)」·Sketchfab 「One Piece Kuzan」')
a('다른세계_나나미_치아키','에노시마 준코','Junko Enoshima,Enoshima','H 「원본 캐릭터는 에노시마 준코(단간론파)」')
a('다른세계_모리야_스와코','콘파쿠 요우무','Youmu Konpaku,Youmu','H 「콘파쿠 요우무(동방 프로젝트)」')
a('다른세계_무면허_라이더','무면허 라이더','Mumen Rider','H 「Mumen Rider, 원펀맨」')
a('다른세계_브로리','브로리','Broly,전설의 초사이어인 브로리','H 「전설의 초사이어인 브로리(드래곤볼 Z)」')
a('다른세계_올마이트','올마이트','All Might','H 「올마이트(나의 히어로 아카데미아)」')
a('다른세계_한마_유지로','한마 유지로','Yujiro Hanma','H 「Yujiro Hanma FBX」')
a('다른세계_호시노_루비','키리기리 쿄코','Kyoko Kirigiri,Kirigiri','H 「캐릭터: 키리기리 쿄코 — 단간론파 VR」')
# 랜덤
a('랜덤_가사이_유노','가사이 유노','Yuno Gasai','H 「미래일기 가사이 유노」')
a('랜덤_김건모','디아볼로','Diavolo','H 「죠죠 5부 디아볼로」')
a('랜덤_리바이_아커만','리바이 아커만','Levi Ackerman,Levi','H 「진격의 거인 리바이 아커만」')
a('랜덤_모몬가','아인즈 울 고운','Ainz Ooal Gown,Ainz,모몬','H 「오버로드 아인즈」')
a('랜덤_미도리야_이즈쿠','미도리야 이즈쿠','Izuku Midoriya,Deku,데쿠','H 「나의 히어로 아카데미아 미도리야 이즈쿠」')
a('랜덤_손오공','손오공','Goku,Son Goku,Songoku','H 「드래곤볼 손오공」')
a('랜덤_야사카_카나코','플랑드르 스칼렛','Flandre Scarlet,Flandre','H 「동방 프로젝트 플랑드르 스칼렛」')
a('랜덤_이민형','키라 요시카게','Yoshikage Kira,Kira','H 「죠죠 4부 요시카게 키라」')
a('랜덤_이즈미_신이치','신몬 베니마루','Benimaru Shinmon,Benimaru','H 「신몬 베니마루(불꽃 소방대)」')
a('랜덤_이타도리_유지','이타도리 유지','Yuji Itadori,Itadori','H 「주술회전 이타도리 유지」')
a('랜덤_주호페이크','쿠죠 죠타로','Jotaro Kujo,Jotaro','H 「죠죠 4부 쿠죠 죠타로」')
a('랜덤_카마도_탄지로','카마도 탄지로','Tanjiro Kamado,Tanjiro','H 「귀멸의 칼날 카마도 탄지로」')
a('랜덤_한마_바키','한마 바키','Baki Hanma,Baki','H 「그래플러 바키, 한마 바키」')
a('랜덤_호시노_아이','아리마 카나','Kana Arima,Arima Kana','H 「oshi-no-ko-arima-kana」(최애의 아이)')
# 변화됨(재료 스킨 그대로)
a('변화됨_강재규','마히토','Mahito','C 재료 희귀함_강재규와 같은 스킨')
a('변화됨_김건','제파','Zephyr,Zeff','C 재료 전설적인_김건과 같은 스킨')
a('변화됨_박은석','바솔로뮤 쿠마','Bartholomew Kuma,Kuma','C 재료 전설적인_박은석과 같은 스킨')
a('변화됨_최상호','히소카','Hisoka','C 재료 희귀함_최상호_윤식파의두뇌와 같은 스킨')
# 불멸
a('불멸_고도현','센고쿠','Sengoku,불상형','H 「센고쿠 불상형, pl_sengoku_orig02」')
a('불멸_김용태','얌마 리야르고','Yammy Llargo,Yammy','H 「얌마 리야르고, Bleach Mobile」')
a('불멸_박은석','몽키 D. 가프','Monkey D. Garp,Garp,가프','H 「몽키 D. 가프(OPFP XPS)」')
a('불멸_신지우','빅맘','Big Mom,샬롯 링링','H 「원피스 빅맘」')
a('불멸_이승우','가로우','Garou','H 「가로우 우주적 공포 모드, 원펀맨」')
a('불멸_이이삭','에드워드 뉴게이트','흰수염,Whitebeard,Newgate','H 「흰수염 에드워드 뉴게이트 전성기」')
a('불멸_정윤식','골 D. 로저','Gol D. Roger,Roger,로저','H 「골 D. 로저」')
a('불멸_정준영','몽키 D. 드래곤','Monkey D. Dragon,Dragon,드래곤','H 「몽키 D. 드래곤」')
# 안흔함
a('안흔함_강재규','재규어','Jaguar','H 「재규어」(동물)')
a('안흔함_강주혁','코알라 키메라 앤트','Koala,키메라 앤트,Chimera Ant','T Sketchfab 「hxh__koala_chimera_ant」','중간')
a('안흔함_김경현','상디','Sanji,Vinsmoke Sanji','F 원본 파일명 「sanji kuroasi.fbx」')
a('안흔함_김민준','곤 프릭스','Gon Freecss,Gon','T Sketchfab 「gon-freecss」')
a('안흔함_김수빈','나나치','Nanachi','F 원본 파일명 「nanachi.glb」(메이드 인 어비스)','중간')
a('안흔함_김용태','젊은 올마이트','All Might,올마이트','H 「젊은 올마이트(나의 히어로 아카데미아)」')
a('안흔함_문필환','우치하 사스케','Sasuke Uchiha,Sasuke','T 「Naruto Shippuden Clash of Ninja Revolution 3 - Sasuke」')
a('안흔함_박민수','덴지','Denji,Pochita,포치타','T Sketchfab 「denji_and_pochita」')
a('안흔함_박준희','사이렌 헤드','Siren Head','H 「사이렌헤드」')
a('안흔함_신문철','','Capoeira','F 원본 파일명 「Capoeira.fbx」(Mixamo 모션 이름 — 캐릭터 아님)','모름')
a('안흔함_엄태웅','한마 바키','Baki,Baki Hanma','F 원본 파일명 「Baki.fbx」')
a('안흔함_이재윤','','monkey','F 원본 파일명 「monkey.FBX」(원숭이 — 캐릭터 불명)','모름')
a('안흔함_이호준','볼보이 좀비','Ball boy zombie','H 「볼보이 좀비」','중간')
a('안흔함_좀비','에밀리아','Emilia','Z 원본 「potk-emilia.zip」(출처 미확인)','중간')
a('안흔함_황정기','','Mixamo','F 원본 파일명 export_….fbx(Mixamo — 캐릭터 불명)','모름')
# 영원
a('영원_김영원','가마분타','Gamabunta,두꺼비','H 「나루토 가마분타 — 두꺼비」')
a('영원_김정래','우라하라 키스케','Kisuke Urahara,Urahara','H 「블리치 우라하라 키스케(시해)」')
a('영원_문필환','히츠가야 토시로','Toshiro Hitsugaya,Hitsugaya,효린마루','H 「블리치 히츠가야 토시로 만해」')
a('영원_서민성','복마어주자','Malevolent Shrine,스쿠나 영역','H 「복마어주자(주술회전, 스쿠나의 영역 사당)」')
a('영원_윤현모','시키','Shiki,Golden Lion','H 「원피스 바운티러시 시키」')
a('영원_이지원','','','H 「파란 동물 후드 잠옷/키구루미 — 캐릭터 이름 없음」','모름')
a('영원_조세민','빌리 타이버','Willy Tybur,Tybur','H 「진격의 거인 빌리 타이버」')
a('영원_최상호','','','H 「나비/나방 날개 달린 캐릭터」 — 이름 없음','모름')
# 전설적인
a('전설적인_구주호','사도 야스토라','Yasutora Sado,Chad,채드','H 「블리치 사도 야스토라 거인의 오른팔」')
a('전설적인_김건','제파','Zephyr,Zeff','H 「전설적인_이시원(제파)과 같은 원본」')
a('전설적인_김민규','우치하 오비토','Obito Uchiha,Obito,토비','H 「나루토 우치하 오비토(토비)」')
a('전설적인_김민준','키자루','Kizaru,Borsalino,보르살리노','H 「원피스 바운티러시 키자루」')
a('전설적인_김용태','카이도','Kaido','H 「원피스 바운티러시 카이도」')
a('전설적인_김정래','브루노 부차라티','Bruno Bucciarati,Bucciarati,부차라티','H 「브루노 부차라티, JoJo Diamond Records」')
a('전설적인_노태현','히구루마 히로미','Hiromi Higuruma,Higuruma,저지맨','H 「주술회전 히구루마 히로미 + 식신 저지맨」')
a('전설적인_박민석','모하메드 압둘','Muhammad Avdol,Avdol','H 「모하메드 압둘, JoJo Diamond Records」')
a('전설적인_박민수','덴지(악마)','Chainsaw Man,체인소맨,Denji','H 「체인소맨 악마 모습(덴지)」')
a('전설적인_박병규','디오 브란도','DIO,Dio Brando,디오','H 「죠죠 디오(각성)」')
a('전설적인_박성호','시바 간쥬','Ganju Shiba,Ganju','H 「블리치 시바 간쥬」')
a('전설적인_박은석','바솔로뮤 쿠마','Bartholomew Kuma,Kuma','H 「원피스 바솔로뮤 쿠마(pl_bkuma)」')
a('전설적인_백기현','우르즈','Urouge','H 「원피스 바운티러시 우르즈」')
a('전설적인_신문철','나루토','Naruto,선인모드,Sage Mode','H 「나루토, 선인모드, 프리파이어 콜라보」')
a('전설적인_신지우','샬롯 링링','Big Mom,빅맘,Charlotte Linlin','H 「원피스 빅맘(샬롯 링링)」')
a('전설적인_양문호','봉쿠레','Bon Clay,Mr.2,Bentham','H 「봉쿠레(Mr.2)」')
a('전설적인_양재모','자라키 켄파치','Kenpachi Zaraki,Kenpachi','H 「블리치 자라키 켄파치」')
a('전설적인_엄태웅','포트거스 D. 에이스','Portgas D. Ace,Ace,에이스','H 「원피스 포트거스 D. 에이스」')
a('전설적인_이승우','이치마루 긴','Gin Ichimaru,Gin','H 「블리치 이치마루 긴」')
a('전설적인_이시원','제파','Zephyr,Zeff','H 「원피스 바운티러시 제파」')
a('전설적인_이유선','타시기','Tashigi','H 「Tashigi, One Piece」')
a('전설적인_이일중','샹크스','Shanks','H 「원피스 샹크스 사황」')
a('전설적인_이재윤','하타케 카카시','Kakashi Hatake,Kakashi,카카시','G glb 제목 「Kakashi hatake naruto Seneca」')
a('전설적인_이현주','휴가 히나타','Hinata Hyuga,Hinata,히나타','H 「나루토 휴가 히나타 스킨」')
a('전설적인_임건웅','후지토라','Fujitora,잇쇼,Issho','H 「원피스 후지토라(잇쇼)」')
a('전설적인_임장혁','메노스 그란데','Menos Grande','H 「블리치 메노스 그란데」')
a('전설적인_임채민','조나단 조스타','Jonathan Joestar,Jonathan','H 「Jonathan Joestar, JoJo 1부」')
a('전설적인_임채현','킹콩','King Kong','H 「킹콩(2005 영화판)」')
a('전설적인_정윤식','킹','King,원펀맨 킹','H 「원펀맨 킹」')
a('전설적인_정준영','에드워드 뉴게이트','흰수염,Whitebeard,Newgate','H 「원피스 흰수염 에드워드 뉴게이트」')
a('전설적인_진연서','하루노 사쿠라','Sakura Haruno,Sakura,사쿠라','H 「나루토 하루노 사쿠라」')
a('전설적인_최상호','아이젠 소스케','Sosuke Aizen,Aizen,아이젠','H 「블리치 아이젠 소스케」')
a('전설적인_홍인창','로시난테','Rocinante,코라손,Corazon','H 「돈키호테 로시난테/코라손」')
# 제한
a('제한_강보명','','','Z zip 안 「Wii」·kk2 텍스처 — 캐릭터 불명','모름')
a('제한_김강민','오리모토 리카','Rika Orimoto','H 「디지몬 오리모토 리카」')
a('제한_김민규','우치하 오비토(어린 시절)','Obito Uchiha,Obito,오비토','H 「Obito (Young Cloak Hidden)」')
a('제한_박성호','퍼펙트 셀','Perfect Cell,Cell,셀','H 「퍼펙트 셀, Dragon Ball Sparking Zero」')
a('제한_이유범','길드 테소로','Gild Tesoro,Tesoro,테소로','H 「길드 테소로 pl_tesoro_orig01」')
a('제한_이충민','베가펑크','Vegapunk,Dr. Vegapunk','H 「원피스 베가펑크」')
a('제한_임준성','무토 유기','Yugi Muto,Yugi','H 「유희왕 무토 유기」')
a('제한_전법규','산타나','Santana,기둥의 남자','H 「산타나, JoJo 1부 기둥의 남자」')
a('제한_최영민','빈스모크 이치지','Vinsmoke Ichiji,Ichiji','H 「원피스 빈스모크 이치지」')
# 초월
a('초월_강재규_AP','토니토니 쵸파','Tony Tony Chopper,Chopper,쵸파','H 「토니토니 쵸파, 몬스터 포인트」')
a('초월_강주혁_AP','코마무라 사진','Komamura Sajin,Komamura,코마무라','H 「블리치 코마무라 사진」')
a('초월_구주호_AD','제저스 버제스','Jesus Burgess,Burgess','H 「제저스 버제스 2년 전」')
a('초월_김건_AP','마샬 D. 티치','Marshall D. Teach,Blackbeard,검은수염','T 「Marshall D_ Teach」(검은수염)')
a('초월_김경현_AP','진타','Jinta Hanakari,하나카리 진타','H 「히단자와 진타, Bleach」 — 표기 불일치(하나카리 진타로 추정)','중간')
a('초월_김만경_AD','도플라밍고','Donquixote Doflamingo,Doflamingo','T 「Donquixote Doflamingo」')
a('초월_김민준_AP','음속의 소닉','Speed-o-Sound Sonic,Sonic','T 「Speed-o'+"'"+'-Sound Sonic」')
a('초월_노태현_AP','쿠로츠치 마유리','Mayuri Kurotsuchi,Mayuri','H 「쿠로츠치 마유리, Bleach Mobile」')
a('초월_두유찬_AD','게토 스구루','Suguru Geto,Geto,켄자쿠','H 「게토 스구루/켄자쿠」')
a('초월_박기찬_AD','료멘 스쿠나','Ryomen Sukuna,Sukuna,스쿠나','H 「료멘 스쿠나」')
a('초월_박민석_ADAP','브룩','Brook,Soul King','G glb 제목 「One Piece Brook」')
a('초월_박민수_AD','후시구로 토지','Toji Fushiguro,Toji,토지','H 「주술회전 후시구로 토지」')
a('초월_배성령_AD','킬러','Killer,Massacre Soldier','H 「킬러 오니가시마」')
a('초월_신문철_AP','나루토','Naruto,육도 나루토,Six Paths','H 「육도 나루토」')
a('초월_양재모_AD','아카이누','Akainu,사카즈키,Sakazuki','H 「사카즈키/아카이누」')
a('초월_엄태웅_AD','니지무라 오쿠야스','Okuyasu Nijimura,Okuyasu','H 「죠죠 니지무라 오쿠야스」')
a('초월_유재헌_ADAP','우치하 마다라','Madara Uchiha,Madara','T 「Madara Uchiha」')
a('초월_이재윤_AD','옷코츠 유타','Yuta Okkotsu,Yuta','H 「옷코츠 유타, Jujutsu Kaisen」')
a('초월_이태훈_AP','스모커','Smoker','H 「스모커, 원피스 타임스킵 후」')
a('초월_임장혁_AD','바라간 루이센방','Baraggan Luisenbarn,Baraggan,바라간','H 「바라간 루이센방 해방형」')
a('초월_임채민_AP','유스타스 키드','Eustass Kid,Kid,키드','T 「Eustass Kid」')
a('초월_조성진_AD','바솔로뮤 쿠마','Bartholomew Kuma,Kuma,쿠마','H 「바솔로뮤 쿠마 과거 모습」')
a('초월_최상호_AD','쿠로사키 이치고','Ichigo Kurosaki,Ichigo,이치고','H 「완전 호로화 이치고」')
a('초월_최상호_AP','아이젠 소스케','Sosuke Aizen,Aizen,아이젠','H 「아이젠 소스케 천년혈전」')
a('초월_황준석_ADAP','아오키지','Kuzan,쿠잔,Aokiji','H 「쿠자/아오키지」')
a('초월위습_박은석','바솔로뮤 쿠마','Kuma Slave,Bartholomew Kuma','H 「Kuma Slave(노예가 된 바솔로뮤 쿠마)」')
# 특별함
a('특별함_강주혁','아이언맨','Iron Man','Z 원본 ironman.zip / IronMan.fbx')
a('특별함_고우선','빈스모크 레이쥬','Vinsmoke Reiju,Reiju','T Sketchfab 「reiju」')
a('특별함_김용태','진베','Jinbe,Jinbei','T 「one-piece-bounty-rush-jinbei」')
a('특별함_김정래','','','H 「프로그래머 — 노트북 소품 유닛」(캐릭터 아님)','모름')
a('특별함_김태영','샬로스','Charlos,Charlos Saint,천룡인','Z 원본 「one-piece-bounty-rush-charlos.zip」','중간')
a('특별함_노건완','잉어','Carp','F 원본 「carp_fish.glb」')
a('특별함_노태현','롭 루치','Rob Lucci,Lucci,루치','F 원본 「pl_lucci_orig02.fbx」')
a('특별함_박기찬','드라큘 미호크','Dracule Mihawk,Mihawk,미호크','T Sketchfab 「mihawk」')
a('특별함_박민석','불렛','Bullet,Bullet(원피스)','F 원본 「pl_bullet_stam01.fbx」','중간')
a('특별함_박민수','가렌','Garen','T Sketchfab 「garen_league_of_legends_character」')
a('특별함_박예원','사보','Sabo','T 「one_oiece_bounty_rush_sabo_stampede」')
a('특별함_박진웅','이토시 린','Rin Itoshi,Itoshi Rin','T 「rin-itoshi-free-fire-skin」')
a('특별함_배성령','사이타마','Saitama','T 「saitama_everyday_opm」')
a('특별함_서아인','','','F 「psychopath_hunt.glb」 — 캐릭터 불명','모름')
a('특별함_송형성','','Adio','Z 원본 「one-piece-bounty-rush-adio.zip」 — 이름만 확인(한글 표기 불명)','모름')
a('특별함_압살롬','메구밍','Megumin','Z 원본 「potk-megumin.zip」(출처 미확인)','중간')
a('특별함_양재모','트라팔가 로','Trafalgar Law,Law,로','F 원본 「pl_law_wano01.fbx」')
a('특별함_왕승환','','strong knight','F 「strong_knight.glb」 — 캐릭터 불명','모름')
a('특별함_유재헌','가로우','Garou','T Sketchfab 「garouopm」')
a('특별함_이병준','','Indian Man In Kurta','T Sketchfab 「Indian Man In Kurta」 — 캐릭터 아님','모름')
a('특별함_이정범','쿠로사키 잇신','Isshin Kurosaki,Isshin','T Sketchfab 「isshin_kurosaki」')
a('특별함_이지원','요크','York','Z 원본 「one-piece-bounty-rush-york.zip」','중간')
a('특별함_이현빈','몽블랑 노랜드','Montblanc Noland,Noland,놀랜드','T 「one-piece-bounty-rush-nolan」')
a('특별함_임장혁','스모커','Smoker','H 「원피스 스모커, pl_smoker_2yaf01」')
a('특별함_임채준','게코 모리아','Gecko Moria,Moria,모리아','T 「one-piece-gecko-moria-marineford」')
a('특별함_정승준','류마','Ryuma','Z 원본 「one-piece-bounty-rush-ryuma.zip」')
a('특별함_조도연','탐 켄치','Tahm Kench','T 「league_of_legend_fan_arttahm_kench」')
a('특별함_조성진','다이아몬드 조즈','Diamante Jozu,Jozu,조즈','T 「one-piece-bounty-rush-jozu」')
a('특별함_조세민','Mr.5','Mr. 5','T 「one-piece-bounty-rush-mr-5」')
a('특별함_주영호','','orc','F 「stylised_orc_model.glb」 — 오크(캐릭터 불명)','모름')
a('특별함_최동준','','','T 「free_download_athletic_african_man_walking」 — 스캔(캐릭터 아님)','모름')
a('특별함_최상호','몽키 D. 루피','Monkey D. Luffy,Luffy,루피','F 원본 「luffy.glb」')
a('특별함_최준우','베르고','Vergo','F 「onepiece_figure_vergo.glb」')
a('특별함_황정기','우솝','Usopp','T 「one-piece-fighting-path-usopp-onigashima」')
# 특수함
a('특수함_BJ_율희','코퀴토스','Cocytus','H 「오버로드 코퀴토스」')
a('특수함_임재현','쿄라쿠 슌스이','Shunsui Kyoraku,Kyoraku','H 「블리치 쿄라쿠 슌스이」')
a('특수함_장명자','엔리코 푸치','Enrico Pucci,Pucci','H 「죠죠 스톤 오션 엔리코 푸치」')
a('특수함_장진희','샤르티아 블러드폴른','Shalltear Bloodfallen,Shalltear','H 「오버로드 샤르티아」')
a('특수함_헬로우먼','케니 아커만','Kenny Ackerman,Kenny','T 「Aotwa kenny ackerman」')
a('특수함_황길라','알베도','Albedo','H 「오버로드 알베도」')
# 흔함
a('흔함_강재규','쵸파','Tony Tony Chopper,Chopper,토니토니 쵸파','F 원본 「Chopper.FBX」')
a('흔함_강주혁','시저 클라운','Caesar Clown,Caesar','F 원본 「pl_caesar_orig01.fbx」')
a('흔함_노태현','롭 루치','Rob Lucci,Lucci,루치','T 「one-piece-bounty-rush-lucci」')
a('흔함_문필환','','','F 원본 「12017 (merge).fbx」 — 캐릭터 불명','모름')
a('흔함_박민석','마젤란','Magellan','F 원본 「pl_magellan_orig01.fbx」')
a('흔함_박민수','블루노','Blueno','H 「원피스 블루노 CP9」')
a('흔함_양재모','자브라','Jabra','H 「원피스 자브라」')
a('흔함_임장혁','프랑키','Franky,프랑키 펑크','F 원본 「pl_franky_punk01 (merge).fbx」')
a('흔함_최상호','나루토','Naruto','H 「나루토, Mixamo 오토리그」','중간')
# 희귀함
a('희귀함_강보명','나란챠 기르가','Narancia Ghirga,Narancia,나란차','H 「나란챠 ギルガ, JoJo Diamond Records」')
a('희귀함_강재규','마히토','Mahito','H 「Mahito」')
a('희귀함_강주혁','젠인 나오야','Naoya Zenin,Naoya','H 「주술회전 젠인 나오야」')
a('희귀함_고어진','하나미','Hanami','H 「Hanami」')
a('희귀함_구주호','사도 야스토라','Yasutora Sado,Chad,채드','H 「블리치 사도 야스토라(채드)」')
a('희귀함_김경현','이타도리 유지','Yuji Itadori,Itadori','H 「주술회전 이타도리 유지」')
a('희귀함_김기연','에렌 예거','Eren Yeager,Eren','H 「진격의 거인 에렌 예거」')
a('희귀함_김만경','오오와다 몬도','Mondo Owada,Owada','H 「오오와다 몬도(단간론파)」')
a('희귀함_김정래','오카베 린타로','Rintaro Okabe,Okabe,오카베','H 「슈타인즈 게이트 오카베 린타로」')
a('희귀함_김청운','에렌 예거','Eren Yeager,Eren','H 「희귀함_김기연과 같은 원본」')
a('희귀함_노수신','시류','Shiryu','H 「원피스 바운티러시 시류」')
a('희귀함_노태현','마르코','Marco,불사조 마르코','H 「원피스 바운티러시 마르코」')
a('희귀함_두유찬','레오리오','Leorio,Leorio Paradinight','H 「헌터x헌터 레오리오」')
a('희귀함_박기찬','그림죠 재거잭','Grimmjow Jaegerjaquez,Grimmjow,그림죠','H 「블리치 그림죠 재거잭」')
a('희귀함_박도진','','','H 「사무라이 소드 — 긴 코트」 — 이름 없음','모름')
a('희귀함_박민수','덴지','Denji','H 「체인소맨 덴지」')
a('희귀함_박수찬','코토부키 히비키','Hibiki Kotobuki,Hibiki','H 「코토부키 히비키」')
a('희귀함_박은석','갑옷 거인','Armored Titan,Reiner,라이너','H 「진격의 거인 갑옷거인」')
a('희귀함_배병규','쿠죠 죠타로','Jotaro Kujo,Jotaro','H 「죠죠 3부 쿠죠 죠타로」')
a('희귀함_배성령','다비','Dabi','H 「나의 히어로 아카데미아 다비」')
a('희귀함_배현진','미와 카스미','Kasumi Miwa,Miwa','H 「Kasumi Miwa」')
a('희귀함_서민성','죠고','Jogo','H 「주술회전 죠고」')
a('희귀함_선효진','','bodybuilder','H 「보디빌더(스캔)」 — 캐릭터 아님','모름')
a('희귀함_양재모','후즈후','Who\'s-Who,Who is Who','H 「원피스 바운티러시 후즈후」')
a('희귀함_엄태웅','한마 바키','Baki,Baki Hanma','H 「baki(한마 바키 계열)」','중간')
a('희귀함_유재헌','','Light','Z zip 안 「source/Light」 — 이름 한 단어뿐(라이토? 불명)','모름')
a('희귀함_윤현모','','Joseph','Z zip 안 「textures/Joseph.png」 — 조셉 조스타? 불명','모름')
a('희귀함_이상혁','','Big Guy','H 「근육 거구 빅 가이」 — 캐릭터 불명','모름')
a('희귀함_이승우','실버즈 레일리','Silvers Rayleigh,Rayleigh,레일리','H 「원피스 바운티러시 실버즈 레일리」')
a('희귀함_이용민','부머','Boomer','H 「Left 4 Dead 2 Special Infected Boomer」')
a('희귀함_이은엽','우치하 사스케','Sasuke Uchiha,Sasuke','H 「나루토 우치하 사스케(보루토 시기)」')
a('희귀함_이재윤','후시구로 토지','Toji Fushiguro,Toji,토지','H 「Jujutsu Kaisen - Toji Fushiguro」')
a('희귀함_이태훈','심해왕','Deep Sea King','H 「원펀맨 심해왕」')
a('희귀함_임채민','이시마루 키요타카','Kiyotaka Ishimaru,Ishimaru','H 「이시마루 키요타카(단간론파)」')
a('희귀함_장태영','히가시카타 죠스케','Josuke Higashikata,Josuke','H 「히가시카타 죠스케」')
a('희귀함_장하민','리조토 네로','Risotto Nero','H 「리조토 네로」')
a('희귀함_정내연','쿠기사키 노바라','Nobara Kugisaki,Nobara','H 「Nobara Kugisaki」')
a('희귀함_조현규','피즈','Fizz','H 「리그 오브 레전드 피즈」')
a('희귀함_최상호_오타쿠의길','쿠로사키 이치고','Ichigo Kurosaki,Ichigo,이치고','H 「블리치 쿠로사키 이치고(사신 복장)」')
a('희귀함_최상호_윤식파의두뇌','히소카','Hisoka','H 「히소카(헌터x헌터)」')
a('희귀함_최현우','로버트 E. O. 스피드왜건','Robert E. O. Speedwagon,Speedwagon','H 「로버트 E. O. 스피드왜건」')
a('희귀함_현성현','야마다 하나타로','Hanataro Yamada,Hanataro','H 「블리치 야마다 하나타로」')
a('희귀함_황준석','나나미 켄토','Kento Nanami,Nanami','H 「(Nanami)」')
# 히든
a('히든_감탄떡볶이','맥심','Maxim,방주 맥심','H 「원피스 방주 맥심」')
a('히든_김영학','이이다 텐야','Tenya Iida,Iida','H 「나의 히어로 아카데미아 이이다 텐야」')
a('히든_맥주만땅','사우전드 써니호','Thousand Sunny,Sunny,써니호','H 「사우전드 써니호(원피스)」')
a('히든_미소야','고잉 메리호','Going Merry,Merry,메리호','H 「고잉 메리호(원피스)」')
a('히든_뻬꼼','포치타','Pochita','H 「체인소맨 포치타」')
a('히든_서승혁','참월','Zangetsu,잔게츠','H 「블리치 참월(이치고의 참백도 정령)」')
a('히든_석성례','알비다','Alvida','H 「원피스 알비다」')
a('히든_성탄','교자맨','Gyoza Man,도로헤도로','H 「도로헤도로 교자맨」')
a('히든_솔','콘','Kon','H 「블리치 콘」')
a('히든_여은서','야마토','Yamato','H 「원피스 야마토」')
a('히든_이동엽','라분','Laboon','H 「원피스 라분, 고래」')
a('히든_이삭토스트','흑수염 해적단 뗏목','Blackbeard raft','H 「원피스 흑수염 해적단 뗏목」')
a('히든_이요한','에스카노르','Escanor','H 「에스카노르(일곱 개의 대죄)」')
a('히든_전유라','츠무기야 우루루','Ururu Tsumugiya,Ururu,우루루','H 「블리치 츠무기야 우루루」')
a('히든_전주연','아틀라스','Atlas,Vegapunk Atlas','H 「원피스 베가펑크 위성 아틀라스」')
a('히든_정기훈','가뭄의 잭','Jack the Drought,Jack,잭','H 「원피스 가뭄의 잭」')
a('히든_정욱진','토센 카나메','Kaname Tosen,Tosen','H 「블리치 토센 카나메」')
a('히든_최경범','제노스','Genos','H 「원펀맨 데몬 사이보그 제노스」')
a('히든_최윤서','캐럿','Carrot','H 「원피스 밍크족 토끼 캐럿」')
a('히든_한나웅','데마로 블랙','Demaro Black,가짜 루피','H 「원피스 가짜 루피/데마로 블랙」')
a('히든_호치킨','이치라쿠 라멘','Ichiraku Ramen','H 「나루토 이치라쿠 라멘 포장마차」')
a('히든_황정기','크로커다일','Crocodile','H 「황정기 — 크로커다일」')

# Roster에 있지만 Art/Units 폴더가 없어 근거가 없는 둘
a('안흔함_상붕카','','','Art/Units에 SOURCE 없음(자전거 유닛 — 캐릭터 불명)','모름')
a('해적선','','','Art/Units에 SOURCE 없음(배)','모름')

if __name__ == '__main__':
    # 사용: /usr/bin/python3 Tools/skin_alias_data.py  → Tools/skin_alias.csv (UTF-8 BOM 없음, 쉼표 구분·따옴표)
    import csv, os, collections
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'skin_alias.csv')
    with open(out, 'w', encoding='utf-8', newline='') as f:
        w = csv.writer(f)
        w.writerow(['유닛 에셋명', '한국어 캐릭터명', '영문/별칭', '근거', '확신도'])
        for row in sorted(D):
            w.writerow(row)
    c = collections.Counter(r[4] for r in D)
    print(out, dict(c))
